### PR TITLE
Improve Postman compatibility

### PR DESCRIPTION
**Pull request by bookmoons**
Improve compatibility with Postman. Aims for fulfillment of #13.

Some details:
- All listed auth methods convert.
- Variables at all scopes (global collection environment data local) + dynamic convert.
- Prerequest scripts and test scripts are included, including those from folders and the collection.
- A shim implements everything possible from the Postman API.

I've split the shim with an extension point, in an attempt to minimize loaded external modules. It does some feature detection on scripts and imports for the bits it finds. I think it will catch all normal usage. If it's not caught the error message indicates what to import.

For building I've duplicated the approach in the JMeter tool. It bundles on install. On convert everything is deployed to a directory next to the output.

### CODE REVIEW

**Comment by bookmoons** [comment]
A handful of pieces in the API don't seem possible. They all throw an error explaining they're not available. `sendRequest` is the big one.

---

`pm.request`
`pm.response.headers`
`pm.sendRequest`

These all return objects from the [`postman-collection`](http://www.postmanlabs.com/postman-collection/) package. I tried browserifying this package but it hangs k6. I'm not sure what's causing that. The input to `sendRequest` could probalby be handled but that `Response` class it returns seems like too much to duplicate.

---

`request.id`

This is a GUID generated by Postman for a request, but it's completely unavailable in the export. We could generate a random one on conversion but I'm not sure if that would break anything.

---

`cookie.hostOnly`
`cookie.session`
`cookie.storeId`

Seem to not be provided by k6.

---

`responseCode.name`
`responseCode.detail`
`pm.response.to.have.status(reason)`
`pm.response.to.not.have.status(reason)`

These all use the textual response message which is not available in the k6 API.

**Comment by bookmoons** [comment]
I have all requests going through the shim via `postman[Request]()`. This handles making everything work with Postman semantics. Prerequest scripts are run with unmodified request details, then the auth is applied, then test scripts are run with modified request details. The shim calls out to k6 at the right points.

```js
// Auto-generated by the Load Impact converter

import "./bundle/shim/core.js";
import URI from "./bundle/urijs.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");

export default function() {
  postman[Request]({
    name: "TestRequest",
    method: "GET",
    address: "http://example.com",
    auth(config, Var) {
      const address = new URI(config.address);
      address.username("user123");
      address.password("secret");
      config.address = address.toString();
      config.options.auth = "basic";
    }
  });
}
```

**Comment by robingustafsson** [comment]
Just wanted to say I'm still reviewing this, just takes a while as there's a lot of code and functionality to test 😅I'm impressed with your work!

A few general things:
- It would be great if we could have the conversion output be similar to what we ended up doing with the jmeter-to-k6 converter (output a script + "vendor"/"libs" folder in specified output directory): https://github.com/loadimpact/jmeter-to-k6/pull/10
- The converter errors out if collection format is v2.1, is that version difficult to support?

**Comment by bookmoons** [comment]
Thank you! Will update / look into both of these.

**Comment by bookmoons** [comment]
Updated those directories.

Collections are accessed through `postman-collection`, which says it supports v2 and v2.1. So I think it will be OK. I've turned it on. It seems to work in a quick test.

**Comment by robingustafsson** [comment]
Ok, pardon the delay. Took a while to get through all features 😃Overall, really well done!

## General
- Would it be a lot of work to add a CLI option to output each request as a separate JS file with a main JS file that imports and calls each request JS file in sequence (the default still being all in one JS file)? Something like:
    ```js
    import request1NameSnakeCased from "./requests/request1NameSnakeCased.js";
    import request2NameSnakeCased from "./requests/request2NameSnakeCased.js";
    ...

    export function default() {
        requestNameSnakeCased();
        request2NameSnakeCased();
        ...
    }
    ```

## API
- There are a couple of error message that needs to be updated to refer to `./libs` instead of `./bundle` in core.js
- `pm.request.url` is not supported as you mention in a comment above, why is it not possible to implement? k6 has a `http.Response.request.url` property (see https://docs.k6.io/docs/response-k6http). Seems to work by just returning `store.request.url` from that function in `core.js`, but I'm likely missing some more complex nuance of how the Postman shim works 🙂
- `pm.request.headers` and `pm.response.headers` is not supported as you mention in a comment above, why is it not possible to implement? k6 has `http.Response.request.headers` and `http.Response.headers` properties (see https://docs.k6.io/docs/response-k6http). [HeaderList](http://www.postmanlabs.com/postman-collection/HeaderList.html) would need to implemented I guess, is that the blocker?
- `pm.info.requestId` throws an exception, but if I read the docs correctly we should instead generate a UUID if there's not an `id` property defined for a request item (https://www.postmanlabs.com/postman-collection/Request.html):
    > or let the system auto generate a UUID if one is not defined
- `pm.info.iterationCount` always returns 1, but it should return whatever `options.iterations` is set to, if set, or `Number.POSITIVE_INFINITY` otherwise (meaning it's a duration-based test run, rather than one based on iterations). Note that there seems to be a bug in how k6 re-injects the `options` var into the runtime as I had to use `parseInt(JSON.stringify(options.iterations))` to get an int rather than an object.

## Auth
- The OAuth1 example I created fails with (see [this gist](https://gist.github.com/robingustafsson/6bd1ed07009e4ed9fb73ffedfbdfc38c)):
```js
ERRO[0012] TypeError: Can`t call method on  null
  at core-js/shim.min.js:7:4993(11)
  at core-js/shim.min.js:7:2405(6)
  at assign (core-js/shim.min.js:7:31705(22))
  at auth (/<path-to>/postman-to-k6/pr-review/oauth/test.js:43:20(60))
```
- The AWS v4 auth example I created fails with a `400 Bad Request`. Can you spot what I'm doing wrong (see [this gist](https://gist.github.com/robingustafsson/799477e447e2889872e74c345f06ded6))?

## CSV/JSON data variables
- The CSV/JSON data file should be copied to the output folder. The path to `open()` currently fails to resolve as it can be a relative path.

**Comment by bookmoons** [comment]
Thank you very much. Going through all of this.

**Comment by bookmoons** [comment]
>Would it be a lot of work to add a CLI option to output each request as a separate JS file

I'm pretty spent for the amount of this bounty. I could take it up under another issue.

---

>`pm.request.url` is not supported as you mention in a comment above, why is it not possible to implement?

This is because of the `postman-collection` API. It returns a [`Url`](http://www.postmanlabs.com/postman-collection/Url.html). People could be using this for structured manipulation of the URL, eg:

```js
const url = pm.request.url
url.addQueryParams({
  session: 'abc123',
  token: '987654'
})
// New URL in url.toString()
```

That class uses `PropertyList` of `QueryParam` and a `VariableList`, and who knows what else at further remove. If I tried to implement this it would snake out into implementing several different classes. I think it's too much to do.

If there were a way to make `postman-collection` run under k6, this would become easy.

The URL is available as a string through the global variable `request`, but that doesn't give the whole `Url` API:
* `request.url`

---

>`pm.request.headers` and `pm.response.headers` is not supported as you mention in a comment above, why is it not possible to implement?

Yeah, just as you say it's that `HeaderList` class. Making `postman-collection` run would also make this one easy.

There are alternatives for this one that I think provide complete functionality, with just standard JS objects:
* `postman.getResponseHeader`
* `request.headers`
* `responseHeaders`

---

>`pm.info.requestId` throws an exception, but if I read the docs correctly we should instead generate a UUID if there's not an `id` property defined for a request item 

I can add this if you want it. Wasn't sure if it should be done or not.

The Postman app seems to generate an ID for each request object when it's created. The ID is static, it's unchanged across runs. So I wondered if people are matching these IDs in scripts, eg in a collection level script that runs for several requests:

```js
if ([
  '6c131dfe-76a8-4e00-9753-fd77abf1d55f',
  '5bc2cc71-baeb-4589-ba07-79cf8f08aeae',
  '8d449d33-debd-49b0-b643-49084e7e51c8'
].includes(pm.info.requestId)) {
  // Common preparation for these 3 requests
}
```

If we changed the IDs it would break the match and this script would start behaving differently. Not really sure if this is a problem or not.

**Comment by bookmoons** [comment]
I think the rest of these are updated / fixed. That oauthbin service is so nice.

For AWS, it seems like the variables are not defined. There's `AWS_ACCESS_KEY` and `AWS_SECRET_KEY`. If you define those somewhere in Postman, maybe under the request, they should show up.

I've tweaked shim deployment to make testing a little easier. If you do `npm run bundle` it will bring you up to date.

**Comment by bookmoons** [comment]
> For AWS, it seems like the variables are not defined.

Realized you might have just left this out of the gist. I did correct something in the address construction, so it's worth trying again.

**Comment by robingustafsson** [comment]
>> Would it be a lot of work to add a CLI option to output each request as a separate JS file

> I'm pretty spent for the amount of this bounty. I could take it up under another issue.

Totally understand, and I'm glad you say it. Will create a new issue for it.

>> pm.request.url is not supported as you mention in a comment above, why is it not possible to implement?

> This is because of the postman-collection API

Yeah, that's what I suspected. Will talk to the k6 team about this, to see if we can figure out why it hangs k6. Can create separate issues for this as well later if we figure out how to solve it.

> I think the rest of these are updated / fixed. That oauthbin service is so nice.

Great! Have checked and can confirm the issues I reported have been fixed. Yup, oauthbin service is nice for testing.

>> pm.info.requestId throws an exception, but if I read the docs correctly we should instead generate a UUID if there's not an id property defined for a request item

> I can add this if you want it. Wasn't sure if it should be done or not.

Yes, please add the UUID. Reading the docs some more it seems to be useful when building "workflows", controlling the order of requests when using the runner: https://learning.getpostman.com/docs/postman/collection_runs/building_workflows/. A see there's an API in that article that I've missed as well, `postman.setNextRequest()`, for this purpose. We can consider implementing that API in a separate issue as well 🙂

>>For AWS, it seems like the variables are not defined.

> Realized you might have just left this out of the gist. I did correct something in the address construction, so it's worth trying again.

Yes, I removed the tokens from the gist 🙂

Sent you a message on Slack as well if you could have a look.

**Comment by bookmoons** [comment]
Alright, that UUID is in. Also added an error for `postman.setNextRequest`.

**Comment by robingustafsson** [comment]
Great, then I'm happily accepting & merging this PR, you can go claim the bounty. Thanks once again for a job well done!

**Pull request merged**
