### PR TITLE
Support file upload

### LINKED ISSUE #42: TypeError: Object has no member ‘replace’
As mentioned in:
https://community.k6.io/t/typeerror-object-has-no-member-replace/253

"Hi

I’ve just converted a postman collection through postman-to-k6 tool.

I’m having the current problem when executing the script and it seems to be connected to http.file part

I’m out of clues about what is happening here

code:
```
export default function() {
		
  postman[Request]({
    name: "/recommendation (file upload)",
    id: "72996999-1924-45d4-8b65-1e1867785397",
    method: "POST",
    address: "{{recommendation-url}}/recommendation?start=1&limit=10",
    data: { user_id: "5", file: http.file(document_file) },
    headers: {
      "Content-Type": "application/json"
    },
    post(response) {
      var jsonData = JSON.parse(responseBody);
      postman.setEnvironmentVariable(
        "recommendation_request.id",
        jsonData.recommendation_request.id
      );
    }
  });
```
Error raised while running the script:
```
ERRO[0005] TypeError: Object has no member 'replace'
        at makeRequestConfig (file:///C:/Users/marcelodalmeida/Desktop/entulho/B-Finder/libs/shim/core.js:996:205(117))
        at executeRequest (file:///C:/Users/marcelodalmeida/Desktop/entulho/B-Finder/libs/shim/core.js:960:35(78))
        at executeRequest (file:///C:/Users/marcelodalmeida/Desktop/entulho/B-Finder/libs/shim/core.js:956:234(53))
        at file:///C:/Users/marcelodalmeida/Desktop/entulho/B-Finder/libs/shim/core.js:307:46(35)
        at file:///C:/Users/marcelodalmeida/Desktop/entulho/B-Finder/recommendation-k6-script.js:37:19(31)
    done [==========================================================] 1 / 1
```
Thank you in advance"

P.S. It is uploading a word document (binary)

### PR DESCRIPTION
**Pull request by bookmoons**
Adds support for the file upload feature of Postman collections.

Postman usage is in the request body interface with a type `form-body`. Each entry can be converted to a file and have a path specified. Hovering reveals the control.

Postman seems to always use absolute paths. The conversion preserves paths and leaves the files where they are.

Closes #42.

### CODE REVIEW

**Comment by bookmoons** [comment]
Here's a collection that uploads the httpbin and displays the result.

```json
{
	"info": {
		"_postman_id": "de6446a1-6b5f-4006-b438-1fe70466daf8",
		"name": "File Upload",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "TestFileUpload",
			"event": [
				{
					"listen": "test",
					"script": {
						"id": "e41d8c08-1399-4956-a5f9-175f90e6eade",
						"exec": [
							"console.log(pm.response.text());",
							""
						],
						"type": "text/javascript"
					}
				}
			],
			"request": {
				"method": "POST",
				"header": [],
				"body": {
					"mode": "formdata",
					"formdata": [
						{
							"key": "file",
							"type": "file",
							"src": "theultimatequestion.txt"
						}
					]
				},
				"url": {
					"raw": "http://httpbin.org/post",
					"protocol": "http",
					"host": [
						"httpbin",
						"org"
					],
					"path": [
						"post"
					]
				}
			},
			"response": []
		}
	],
	"protocolProfileBehavior": {}
}
```

It looks for a file `theultimatequestion.txt` in the same dir, eg:

```
Test data
```

**Comment by bookmoons** [comment]
@marcelo-dalmeida I wonder if you'd be willing to test this with your collection? It would help to confirm it does the right thing with real input.

**Comment by marcelo-dalmeida** [comment]
@bookmoons 

I'm doing it now

**Comment by marcelo-dalmeida** [comment]
@bookmoons 

Feel free to ask me to test it anytime you need

Here a snippet from my attempt:

image

**Comment by bookmoons** [comment]
Whoops, my fault. Got to have an `npm install` in there to install deps.

```
git clone https://github.com/bookmoons/postman-to-k6.git
cd postman-to-k6
git branch bookmoons/file-upload
npm install
node bin/postman-to-k6.js collection.json
```

**Comment by marcelo-dalmeida** [comment]
image

**Comment by bookmoons** [comment]
Really need to test my instructions before posting. Branch was the wrong command. Checkout is the right thing. This gets it to the right code for me.

```sh
git checkout master
git branch -D bookmoons/file-upload
git checkout bookmoons/file-upload
npm install
node bin/postman-to-k6.js collection.json
```

**Comment by marcelo-dalmeida** [comment]
Hi @bookmoons 

Sorry, I could have noted it too.


For the problem at matter

That's the generated file:
[k6-script.zip](https://github.com/loadimpact/postman-to-k6/files/3763852/k6-script.zip)

I now find the original error (as you noted in the issue, it was two different errors):
image

So I think it may be better to create another issue and associate this pull request to that

Also, thank you for working on it

**Comment by bookmoons** [comment]
Is it possible you were executing the old conversion here? The conversion seems to work for me. Here's a tested script that pulls and converts. It doesn't find the upload file on my system but it should be there on yours.

```shell
#!/bin/bash

git clone https://github.com/bookmoons/postman-to-k6.git
cd postman-to-k6
git checkout bookmoons/file-upload
npm install
wget https://github.com/loadimpact/postman-to-k6/files/3745258/recommendation.postman_collection.zip
unzip recommendation.postman_collection.zip
rm recommendation.postman_collection.zip
node bin/postman-to-k6.js recommendation.postman_collection.json >upload.js
k6 run upload.js
```

I think it will also find a missing environment. In Postman you can export the environment, then the converter can take it on the command line.

```
node bin/postman-to-k6.js recommendation.postman_collection.json -e environment.json >upload.js
```

Also pushed a fix for paths, Postman seems to encode a Windows path a little differently.

**Comment by marcelo-dalmeida** [comment]
Hi @bookmoons 

> Is it possible you were executing the old conversion here?

Recapitulating my actions:

Well, I cleaned as you instructed:
> ```shell
> git checkout master
> git branch -D bookmoons/file-upload
> git checkout bookmoons/file-upload
> npm install
> node bin/postman-to-k6.js collection.json
> ```

Then I saw file info that was not present before in the script. So I tested with run as the conversion seemed fine to me. I also sent you the file so you could double-check what I was running
> That's the generated file:
> [k6-script.zip](https://github.com/loadimpact/postman-to-k6/files/3763852/k6-script.zip)
> 
> I now find the original error (as you noted in the issue, it was two different errors):
> image

It seemed 'double-fine' to me as it was giving me the very same error I found when I manually fixed the file part of the script. It was then a matter about the file being binary.

Now I ran the conversion again (from the scratch) and included the missing environment.
image

**Comment by marcelo-dalmeida** [comment]
[B-Finder Copy.postman_environment.zip](https://github.com/loadimpact/postman-to-k6/files/3767397/B-Finder.Copy.postman_environment.zip)

I'm sending you a copy, but I just removed 'sensitive' information

**Comment by bookmoons** [comment]
Appreciate the report and testing @marcelo-dalmeida. Pointing your collection at httpbin successfully uploads for me, so I think it's in good shape. After review / possible bug fixes this should land in the next release.

Your collection has a header `Content-Type: application/json`. I had to take this header out to make the upload work. Tests show Postman overrides it automatically.

**Comment by bookmoons** [comment]
I think this is ready for review.

**Comment by robingustafsson** [comment]
Pardon delay in reviewing. LGTM. Merging.

**Pull request merged**
