### PR TITLE
Add request decomposition with directories

### LINKED ISSUE #24: Request decomposition [bounty: $200]
Add a CLI option to output each request in a collection to a separate JS file. Groups should be respected and create necessary folder tree in output directory.

### PR DESCRIPTION
**Pull request by bookmoons**
Adds command line option `--separate/-s` which generates a separate file per request.

Generated files define the request through the shim. The main logic then invokes requests by name.

Files are generated into a directory structure matching the tree defined in the Postman collection. File and folder name collisions are suffixed alphabetically, A B etc.

Closes #24.

### CODE REVIEW

**Comment by bookmoons** [comment]
The `box` example puts this to good use.

```js
export default function() {
  group("Collaborations", function() {
    postman[Request]("Get Pending Collaborations");
    postman[Request]("Retrieve a Collaboration");
    postman[Request]("Retrieve all Collaborations");
    postman[Request]("Add a Collaboration");
    postman[Request]("Edit a Collaboration");
    postman[Request]("Remove a Collaboration");
  });
  group("Comments", function() {
    postman[Request]("Get Information About a Comment");
    postman[Request]("Add a Comment to a File");
    postman[Request]("Add an '@' Comment to a File");
    postman[Request]("Add an Reply Comment to a File");
    postman[Request]("Change a Comment's Message");
    postman[Request]("Delete a Comment");
  });
  group("Events", function() {
    postman[Request]("Get Events for a User");
    postman[Request]("Get a Specific Event in an Enterprise");
    postman[Request]("Get Events in an Enterprise");
  });
  group("Files", function() {
    postman[Request]("Download a File");
    postman[Request]("Get Information about a File");
    postman[Request]("View the Comments on a File");
    postman[Request]("Get a Thumbnail for a File");
..
```

**Comment by robingustafsson** [comment]
Apologies for the delay. Looking at this now. Running the box example from above I get:

```
Could not create request file Collaborations
{ Error: EISDIR: illegal operation on a directory, open './requests/Collaborations'
    at Object.openSync (fs.js:436:3)
    at Object.writeFileSync (fs.js:1168:35)
    at outputRequests (/<path>/postman-to-k6/bin/requests.js:11:10)
    at Command.run (/<path>/postman-to-k6/bin/postman-to-k6.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)
  errno: -21,
  syscall: 'open',
  code: 'EISDIR',
  path: './requests/Collaborations' }
```

Also, I think the filenames should be filtered a bit. The box example produces filenames like `Get the Current User's Information.js` and `Get Access & Refresh Token.js`. I propose we at least filter out characters not matching Unicode's "Letters" and "Numbers" category, or at least replace those other characters with a hyphen.

**Comment by bookmoons** [comment]
Strange. I'll put it on my list to look into this. Thanks for looking it over.

**Comment by bookmoons** [comment]
Think I've got this error fixed, and implemented that filename encoding.

Did the encoding like this:
* Strip everything except `A-Za-z0-9 .-`
* Replace consecutive space sequences with a single `-`

**Comment by robingustafsson** [comment]
@bookmoons Thanks, works and LGTM, merging.

**Pull request merged**
