### PR TITLE
Auth: Implemented ApiKey Authorization

### PR DESCRIPTION
**Pull request by chrispad2k**
This pull request should make the Postman "API Key" Authorization available on collections.

I would appreciate if this feature could be included, it is longingly needed in another project, which also uses postman-to-k6 for automated load testing with Postman Tests.

Kind Regards

Christoph Pader

### CODE REVIEW

**Comment by simskij** [comment]
Hi,

Thank you for your contributions. I'd love to include this, however, the tests are currently failing. Would you mind having a look at that?

Thanks again,
Simme

**Comment by chrispad2k** [comment]
Ok, so i just have one question @simskij ... How are you building the production script (in ./bin, the one that is included with the npm-package), so i can test the functionality before pushing to the repo.. can't seem to find a 'main' property in package.json or any building script.

Kind regards

**Comment by simskij** [comment]
You shouldn't need to build anything. Running the "bin" in `./bin/postman-to-k6.js' will use the code in the lib folder.

**Comment by chrispad2k** [comment]
Ok so locally the tests are succeeding, idk why they are failing in CI/CD...
```
√ auth » apikey

46 tests passed
```

Getting a `Rejected promise returned by test` error

**Comment by chrispad2k** [comment]
@simskij error fixed, tests are passing! :-)
I can confirm the authentication is working and the header is being added.

I still have another question... As of now, `pm.collectionVariables` is not supported or is it? Because when running the generated script `pm.collectionVariables.<key>` throws an error, as it is `undefined`.. Maybe this feature could be implemented or i would have a look at it.

Kind regards

Christoph Pader

**Comment by chrispad2k** [comment]
Hey @simskij ! Is this still being reviewed?

Kind regards
Chris

**Comment by simskij** [comment]
LGTM! Merging. Regarding `collectionVariables`; from what I can tell there is no explicit support for this, sounds great if you'd like to have a look at it. Let me know if I can assist you in any way.

**Pull request merged**
